# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: carcassonne.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61rcassonne.proto\x12\x0b\x63\x61rcassonne\";\n\x06Sender\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.carcassonne.SenderType\x12\n\n\x02id\x18\x02 \x01(\t\"\x1b\n\x0b\x45\x63hoRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1c\n\x0c\x45\x63hoResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\";\n\x10StartGameRequest\x12\x12\n\nnumPlayers\x18\x01 \x01(\x05\x12\x13\n\x0bplayerNames\x18\x02 \x03(\t\"#\n\x11StartGameResponse\x12\x0e\n\x06gameId\x18\x01 \x01(\t\"\xf0\x01\n\x07Payload\x12/\n\x0b\x65\x63hoRequest\x18\x01 \x01(\x0b\x32\x18.carcassonne.EchoRequestH\x00\x12\x31\n\x0c\x65\x63hoResponse\x18\x02 \x01(\x0b\x32\x19.carcassonne.EchoResponseH\x00\x12\x39\n\x10startGameRequest\x18\x03 \x01(\x0b\x32\x1d.carcassonne.StartGameRequestH\x00\x12;\n\x11startGameResponse\x18\x04 \x01(\x0b\x32\x1e.carcassonne.StartGameResponseH\x00\x42\t\n\x07payload\"U\n\x07Message\x12#\n\x06sender\x18\x01 \x01(\x0b\x32\x13.carcassonne.Sender\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.carcassonne.Payload*B\n\nSenderType\x12\r\n\tANONYMOUS\x10\x00\x12\n\n\x06PLAYER\x10\x01\x12\n\n\x06SERVER\x10\x02\x12\r\n\tDEVELOPER\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'carcassonne_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SENDERTYPE']._serialized_start=582
  _globals['_SENDERTYPE']._serialized_end=648
  _globals['_SENDER']._serialized_start=34
  _globals['_SENDER']._serialized_end=93
  _globals['_ECHOREQUEST']._serialized_start=95
  _globals['_ECHOREQUEST']._serialized_end=122
  _globals['_ECHORESPONSE']._serialized_start=124
  _globals['_ECHORESPONSE']._serialized_end=152
  _globals['_STARTGAMEREQUEST']._serialized_start=154
  _globals['_STARTGAMEREQUEST']._serialized_end=213
  _globals['_STARTGAMERESPONSE']._serialized_start=215
  _globals['_STARTGAMERESPONSE']._serialized_end=250
  _globals['_PAYLOAD']._serialized_start=253
  _globals['_PAYLOAD']._serialized_end=493
  _globals['_MESSAGE']._serialized_start=495
  _globals['_MESSAGE']._serialized_end=580
# @@protoc_insertion_point(module_scope)
