# Required
cluster_name: 'Test Cluster'
num_tokens: 256
listen_address: 172.17.0.2
rpc_address: 0.0.0.0
broadcast_rpc_address: 172.17.0.2
seed_provider:
  - class_name: org.apache.cassandra.locator.SimpleSeedProvider
    parameters:
      - seeds: "172.17.0.2"
endpoint_snitch: SimpleSnitch
partitioner: org.apache.cassandra.dht.Murmur3Partitioner

# Commit log
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000

# Auth
authenticator: PasswordAuthenticator
authorizer: CassandraAuthorizer
role_manager: CassandraRoleManager

# Directories (match Docker volume)
data_file_directories:
  - /var/lib/cassandra/data
commitlog_directory: /var/lib/cassandra/commitlog
saved_caches_directory: /var/lib/cassandra/saved_caches

# Native transport
start_native_transport: true
native_transport_port: 9042
